fix: replace error syntax with exit code (#30)

diff --git a/eng/infra/Makefile b/eng/infra/Makefile
--- a/eng/infra/Makefile
+++ b/eng/infra/Makefile
@@ -1,7 +1,8 @@
 variables:
 	@echo "=> Checking environment variables..."
 	@if [[ -z "$(RESOURCE_GROUP)" || -z "$(CLUSTER_NAME)" || -z "$(TENANT_ID)" ]]; then \
-		$(error "Missing required environment variables"); \
+		echo "Missing required environment variables"; \
+		exit 1; \
 	fi
 
 deploy:
diff --git a/src/Pipelines.Images/Makefile b/src/Pipelines.Images/Makefile
--- a/src/Pipelines.Images/Makefile
+++ b/src/Pipelines.Images/Makefile
@@ -1,7 +1,8 @@
 variables:
 	@echo "=> Checking environment variables..."
 	@if [[ -z "$(RESOURCE_GROUP)" || -z "$(CLUSTER_NAME)" || -z "$(REGISTRY_NAME)" || -z "$(IMAGE_NAME)" ]]; then \
-		$(error "Missing required environment variables"); \
+		echo "Missing required environment variables"; \
+		exit 1; \
 	fi
 
 build:
